version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: _docker/app/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    container_name: task_app
    depends_on:
      - db

  db:
    image: mysql:8.4.2
    ports:
      - "8081:3306"
    volumes:
      - ./temp/db:/var/lib/mysql
    container_name: task_db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYQSL_DATABASE=task_ac

    